### ISSUE TITLE
!stats throws internal error

### ISSUE THREAD

**Issue by theianwright** [professor-l/classic-tetris-project#108]
![CTBError](https://github.com/professor-l/classic-tetris-project/assets/31325803/c5795d55-8c6e-4b5b-b30d-70fe6de0c67f)

**Comment by theianwright** [comment]
addressed in [this pull request](https://github.com/professor-l/classic-tetris-project/pull/114)

**Comment by fractal161** [comment]
resolved in fe367eab57c72489f137b6795b2cea1cc63e9c37 (i did this accidentally didn't mean to snipe the pr sry).
