### ISSUE TITLE
!hz command

### ISSUE THREAD

**Issue by alex-ong** [professor-l/classic-tetris-project#11]
> add a !hz command where you input column, level, height and bot gives you effective and minimum speeds

We could draw a markdown diagram, followed by input sequence and finally hz.

eg
!hz 1 18 10

```
1 |          |
2 |          |
3 |          |
4 |          |
5 |          |
6 |          |
7 |X         |
8 |X         |
9 |X         |
10|X         |
  |OOOOOOOOOO|

5 taps, 20 frame window. 
Input sequence:
XOOOXOOOXOOOXOOOX
Hz: 12 ~ 15
```

**Comment by professor-l** [comment]
Actually, I'm 100% a fan of this. I think it's really cool.  #rabbit-hole discussion sometime this evening with you, me, Hydrant, and maybe Kitaru?  xD

**Comment by alex-ong** [comment]
I'm writing a comment.

**Comment by alex-ong** [comment]
test message.
