### ISSUE TITLE
Hz command gif generation is messy

### ISSUE THREAD

**Issue by professor-l** [professor-l/classic-tetris-project#25]
First off, it's just a bunch of functions, and there's top-level code that just *runs*, and that's not the style of our project at all.  Secondly, some of those functions are quite long and could probably be modularized to improve code readability.  It works quite well, but the whole [field_generator.py](https://github.com/professor-l/classic-tetris-project/blob/master/classic_tetris_project/util/fieldgen/field_generator.py) file is kind of a disaster.  It might be worth splitting it up into multiple files (though that's not something I have a strong opinion on), but at the very least the file should have no top-level code aside from imports and constant definitions.  Also, the four pngs should be moved into an `img` subdirectory like I did in [docs](https://github.com/professor-l/classic-tetris-project/tree/master/docs).  

@alex-ong you can make code as chaotic as you want when it's a temporary submodule that points to your own repository, but please try to follow our structure when you're contributing to this one.  You may find it helpful to skim the [architecture write-up](https://github.com/professor-l/classic-tetris-project/blob/master/docs/ARCHITECTURE.md) again for inspiration.  And to fix typos, since it's probably riddled with them xD

**Comment by alex-ong** [comment]
I'll have a look at it tomorrow

**Comment by professor-l** [comment]
Thanks.  It’s not super urgent since it works, just important for consistency and such.
