### ISSUE TITLE
!country [username] returns wrong country

### ISSUE THREAD

**Issue by dbav** [professor-l/classic-tetris-project#37]
Using !country [username] should return the country of the specified user, however, it returns the country of the user that typed the message.

**Comment by alex-ong** [comment]
This is intended behavior. !country username returns the country that the person who typed it wants the user to move to.

:Kappa:

**Comment by hydra314** [comment]
The !country [username] command also pings the subject of the command, which is inconsistent with how other commands of this nature work.

**Comment by alex-ong** [comment]
@hydra314 this is working as intended, so that the subject is notified that their current visa has expired and to move to the requestors country

**Comment by hydra314** [comment]
![image](https://user-images.githubusercontent.com/11010760/89514729-10c51980-d78b-11ea-916a-6f8abf2954c2.png)
The absolute scenes when Batfoy returns to his home country of Mongolia with the CTWC 2020 trophy

**Comment by vansh09122003** [comment]
its not ntworking
ferrow is from germany
![Screenshot (33)](https://user-images.githubusercontent.com/49370661/93187077-0409ed00-f75d-11ea-932b-eb96a763a7eb.png)

**Comment by fractal161** [comment]
resolved in https://github.com/professor-l/classic-tetris-project/commit/36bca2cefe01876530207cadae5ac40766066dd6.
