### ISSUE TITLE
Feature Request: scheduling timezones

### ISSUE THREAD

**Issue by alex-ong** [professor-l/classic-tetris-project#8]
`!settimezone`
(sets users timezone)
This could be est etc but we can look it up and store it in UTC.
Not sure how we would account for daylight savings... do we force users to update every 6 months (unideal) or do we figure shit out?

`!schedule username [monday-sunday]`
Looks up utc offset for the other user, then creates a link below
Creates a link to timeanddate.com:
https://www.timeanddate.com/worldclock/meetingtime.html?iso=20200320&p1=3913&p2=3919

`!schedule utc+x`
same as with username but for noobs who don't set their timezone.

**Comment by professor-l** [comment]
This won't be done through commands, it'll be on the website, and time zones on user profiles is [already a to-do](https://github.com/professor-l/classic-tetris-project/projects/1#card-27227866).  Closing issue.
